[dependencies]
base = "0.12.1"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc1-mo = "0.0.15"
icrc2-mo = "0.0.13"
icrc3-mo = "0.2.6"
icrc4-mo = "0.0.5"
